export enum GenreEnum {

    ACTION = 'ACTION',
    ADVENTURE = 'ADVENTURE',
    ANIMATION = 'ANIMATION',
    COMEDY = 'COMEDY',
    CRIME = 'CRIME',
    DOCUMENTARY = 'DOCUMENTARY',
    DRAMA = 'DRAMA',
    FAMILY = 'FAMILY',
    FANTASY = 'FANTASY',
    HISTORY = 'HISTORY',
    HORROR = 'HORROR',
    MUSIC = 'MUSIC',
    MYSTERY = 'MYSTERY',
    ROMANCE = 'ROMANCE',
    SCIENCE_FICTION = 'SCIENCE_FICTION',
    TV_MOVIE = 'TV_MOVIE',
    THRILLER = 'THRILLER',
    WAR = 'WAR',
    WESTERN = 'WESTERN'
}